/*
 Generated by typeshare 1.0.0
*/

export interface SimpleStruct {
	id: number;
	name: string;
}

export type Command = 
	| { type: "List", content?: undefined }
	| { type: "Detail", content: number };

